name: Security Audit

on:
  push:
    branches:
      - main
    paths:
      - '**/Cargo.toml'
  schedule:
    - cron: '0 9 * * *' # run at 9 AM UTC

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit Check
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
