on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

name: Test sodium-rust

jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
        experimental:
          - false
        include:
          - toolchain: nightly
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # args: -- -D warnings
